### ISSUE TITLE
Build failure - ONBUILD COPY thinks /app/spring-boot.jar is a directory

### ISSUE THREAD

**Issue by CharlyRipp** [f-lopes/spring-boot-docker#1]
This is on Mac OSX -

```
➜ docker build -t test .
Sending build context to Docker daemon   78.2MB
Step 1/3 : FROM flopes/spring-boot-docker:1.1
# Executing 1 build trigger
failed to copy files: failed to copy directory: mkdir /var/lib/docker/overlay2/e037866baf5dd7f90770720a03b4814dd9f275c5f138368bea923f397160e345/merged/app/spring-boot.jar: not a directory
```

**Dockerfile**
```
FROM flopes/spring-boot-docker:1.1
```

I'd almost lean towards removing the `ONBUILD COPY` from your script and leaving it up to the user to perform:
```
FROM flopes/spring-boot-docker:1.1

COPY /target/my-special-named.jar /app/app.jar
```
and always assume it lands as `/app/app.jar`. 

I'm working through another issue where it says it doesn't have access to run:
```
➜ docker run --rm -p 8080:8080 --name testing test
Error: Unable to access jarfile /app/app.jar
```

After adding an overly complex chmod:
```
FROM flopes/spring-boot-docker:modified

COPY target/app.jar /app/app.jar
USER root
RUN chmod 555 /app/app.jar
USER spring-boot
```
I get Invalid/corrupt:
```
➜ docker run --rm -p 8080:8080 --name testing test
Error: Invalid or corrupt jarfile /app/app.jar
```

Going to keep playing, but figured I'd post this to you to see if you knew anything off the top of your head.

**Comment by CharlyRipp** [comment]
Ummm....

![a](https://78.media.tumblr.com/b0c7376fb15f466f8c0545200e49087f/tumblr_nokr07vaix1sd2x2co1_500.jpg)

Turns out everything was caused by my misconfigured build plugin in my `pom` which was dropping the resources, causing the `java -jar` command to see it as corrupt. Somehow this causes OSX to see it as an directory, as you'd see a .war, but I haven't figured out why.

Fixing my plugin made everything operate the way it should without any changes.

I still think the removal of `ONBUILD` to allow copying from a custom location makes sense. Tried adding environment variables to allow an override, but since the `ONBUILD` runs as the first thing, my `ENV` on the child Dockerfile doesn't execute in time to update the path/name.

**Comment by f-lopes** [comment]
Hi @CharlyRipp 
 
 Thanks for your feedback. I also thought about removing the ONBUILD instruction to leave the user the choice of the custom location by overriding the environment variable. As you said, it would perfectly makes sense.
 
 However, doing so would require the parent image to provide a default jar to be able to build it?

Did you think of another way?

**Comment by CharlyRipp** [comment]
Finally getting around to answering you -- only a few months late...

Just tried with a slimmed down version to play:

```
FROM openjdk:8-jre-alpine

ENV DEBUG_PORT=8000 \
    SERVER_PORT=8080 \
    MANAGEMENT_PORT=9000

RUN addgroup -S spring-boot \
 && adduser -S -g spring-boot spring-boot

EXPOSE $DEBUG_PORT $SERVER_PORT $MANAGEMENT_PORT
VOLUME /tmp
WORKDIR /app
USER spring-boot

ENTRYPOINT [[ "$DEBUG" = true ]] && JAVA_OPTS="$JAVA_OPTS -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=$DEBUG_PORT,suspend=n"; \
           exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar
```

Using it via

```
FROM thing/from-above

ADD /target/*.jar /app/app.jar
```

Seems to work just fine. Sad part is you can't use an environment variable in the 2nd dockerfile defined in the first, so `app/app.jar` has to be a well-known drop.

**Comment by f-lopes** [comment]
Thanks for your feedback.

Unfortunately, this caveat is hard to avoid as `app/app.jar` has to be well-known in advance.

Feel free to come back if you want to submit a proposal.
